# Generated by Django 3.1.1 on 2021-03-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('Tecnologia', 'TC'), ('Curiosidades', 'CR'), ('Geral', 'GR')], max_length=12),
        ),
    ]
